---
title: "Actividades de la UVIGO"
---

*Informe estructurado de la actividad de la parte de la participación de la **Universidade de Vigo (UVIGO)** perfectamente definido y fácil de integrar con la del informe de **DROGAS VIGO (DROVI)**.*

## Desarrollo de Disolventes Biobasados y Sistemas de Microemulsiones de Alta Estabilidad

Ángel Sánchez y Ana María González Sánchez\
Escola de Enxeñaría Industrial\
Universidade de Vigo\_

El proyecto **AGROSOLVENTS** ha concluido tras veinticuatro meses de investigación intensiva, representando un avance significativo en la intersección entre la ingeniería química de vanguardia y la sostenibilidad industrial. Este informe documenta exhaustivamente la contribución técnica y científica de la Universidad de Vigo (UVIGO), cuya labor ha sido fundamental para dotar al consorcio de una base teórica robusta y de herramientas de simulación avanzada para la predicción de propiedades fisicoquímicas en mezclas no ideales.1 Bajo la dirección del Departamento de Ingeniería Química, el equipo de UVIGO ha liderado la transición desde el concepto de laboratorio hasta la validación en planta piloto, empleando metodologías que integran la termodinámica de soluciones, el desarrollo de software especializado en Python y la simulación de procesos químicos complejos.

